version: '3.9'
services:
  app:
    container_name: coffee-chess
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      db:
        condition: service_healthy
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    links:
      - cache
      - db
    env_file:
      - .env
  cache:
    container_name: redis
    image: redislabs/rejson:2.4.2
    ports:
      - 3001:6379
  db:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 3002:1433
    environment:
      SA_PASSWORD: dev7aY!dm2t62
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "dev7aY!dm2t62" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
volumes:
  mssql-data:
