version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: nvm install 14.20
      - run: |
          mkdir ~/$KUBE_REPO
          git clone git@github.com:MikeZ77/$KUBE_REPO.git ~/$KUBE_REPO
          cp ~/$KUBE_REPO/.env .
      - run: npm install
      - run: docker run --name db-setup -v project_mssql-data:/var/opt/mssql -e ACCEPT_EULA='Y' -e MSSQL_SA_PASSWORD='dev7aY!dm2t62' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest
      - run: sleep 5
      - run: |
          docker cp ~/$KUBE_REPO/app.bak db-setup:/tmp
          docker cp ~/$KUBE_REPO/restore_app.sql db-setup:/tmp
      - run: docker exec db-setup /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'dev7aY!dm2t62' -i /tmp/restore_app.sql
      - run: docker stop db-setup
      - run: docker-compose up -d
      - run: npm run test
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build --tag mzaghi/coffee-chess:lab .
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker push mzaghi/coffee-chess:lab

  # deploy:
  #   requires:
  #     - build

workflows:
  test_build_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
