version: 2

jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - run: docker build --tag mzaghi/coffee-chess .
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker push mzaghi/coffee-chess
