version: 2.1

jobs:
  test:
    docker:
      - image: ubuntu-2004:2022.10.1
    steps:
      - checkout
      - run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo apt-get install mssql-tools unixodbc-dev
      - run: |
          curl -sL https://deb.nodesource.com/setup_14.20 -o /tmp/nodesource_setup.sh
          sudo bash /tmp/nodesource_setup.sh
          sudo apt install nodejs
      - add_ssh_keys:
          fingerprints:
            - 'N+d9P//Fwoec2qUPIM7U6fRscN9t3UUjzS0kHOBkGUI'
      - run: |
          git clone git@github.com:MikeZ77/$KUBE_REPO.git /tmp
          cp /tmp/$KUBE_REPO/.env .
          cp /tmp/$KUBE_REPO/app.bak .
      - run: npm install
      - run: docker-compose up
      - run: sqlcmd -S localhost,3002 -U SA -Q "RESTORE DATABASE [app] FROM DISK = N'app.bak' WITH FILE = 1, NOUNLOAD, REPLACE, STATS = 5"
      - run: npm run test

  build:
    requires:
      - test
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build --tag mzaghi/coffee-chess:lab .
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker push mzaghi/coffee-chess:lab

  # deploy:
  #   requires:
  #     - build
