version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: nvm install 14.20.1
      - run: |
          mkdir ~/$KUBE_REPO
          git clone git@github.com:MikeZ77/$KUBE_REPO.git ~/$KUBE_REPO
          cp ~/$KUBE_REPO/.env .
      - run: |
          nvm use 14.20.1
          npm install
      - run: docker run --name db-setup -v project_mssql-data:/var/opt/mssql -e ACCEPT_EULA='Y' -e MSSQL_SA_PASSWORD='dev7aY!dm2t62' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest
      - run: sleep 5
      - run: |
          docker cp ~/$KUBE_REPO/app.bak db-setup:/tmp
          docker cp ~/$KUBE_REPO/restore_app.sql db-setup:/tmp
      - run: docker exec db-setup /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'dev7aY!dm2t62' -i /tmp/restore_app.sql
      - run: docker stop db-setup
      - run: docker-compose up -d
      - run: |
          nvm use 14.20.1
          npm run test
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build --tag mzaghi/coffee-chess:${CIRCLE_SHA1} .
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker push mzaghi/coffee-chess:${CIRCLE_SHA1}
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: | 
          curl -LO https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - run: |
          echo "$KUBE_CONFIG" | base64 -d > kubeconfig.yaml
          mkdir ~/.kube
          mv kubeconfig.yaml ~/.kube/config
      - run: |
          mkdir ~/$KUBE_REPO
          git clone git@github.com:MikeZ77/$KUBE_REPO.git ~/$KUBE_REPO
          cp ~/$KUBE_REPO/coffee.yaml .
      - run: sed -i "s|{{IMAGE_TAG}}|${CIRCLE_SHA1}|g" coffee.yaml
      - run: cat coffee.yaml

workflows:
  test_build_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build